// Mocks generated by Mockito 5.4.6 from annotations
// in heart_beat/test/workout/coaching_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:heart_beat/ble/ble_service.dart' as _i2;
import 'package:heart_beat/ble/ble_types.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleService extends _i1.Mock implements _i2.BleService {
  MockBleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.BleConnectionState> get connectionStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStateStream),
            returnValue: _i3.Stream<_i4.BleConnectionState>.empty(),
          )
          as _i3.Stream<_i4.BleConnectionState>);

  @override
  _i3.Stream<int> get heartRateStream =>
      (super.noSuchMethod(
            Invocation.getter(#heartRateStream),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i4.BleConnectionState get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i4.BleConnectionState.idle,
          )
          as _i4.BleConnectionState);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isSupported =>
      (super.noSuchMethod(Invocation.getter(#isSupported), returnValue: false)
          as bool);

  @override
  _i3.Future<void> initializeIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#initializeIfNeeded, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.DeviceInfo?> scanAndConnect({
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#scanAndConnect, [], {#timeout: timeout}),
            returnValue: _i3.Future<_i4.DeviceInfo?>.value(),
          )
          as _i3.Future<_i4.DeviceInfo?>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopScan() =>
      (super.noSuchMethod(
            Invocation.method(#stopScan, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.DeviceInfo>> getKnownDevices() =>
      (super.noSuchMethod(
            Invocation.method(#getKnownDevices, []),
            returnValue: _i3.Future<List<_i4.DeviceInfo>>.value(
              <_i4.DeviceInfo>[],
            ),
          )
          as _i3.Future<List<_i4.DeviceInfo>>);

  @override
  _i3.Future<_i4.DeviceInfo?> connectToDevice(
    String? deviceId, {
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #connectToDevice,
              [deviceId],
              {#timeout: timeout},
            ),
            returnValue: _i3.Future<_i4.DeviceInfo?>.value(),
          )
          as _i3.Future<_i4.DeviceInfo?>);

  @override
  _i3.Future<bool> checkAndRequestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#checkAndRequestPermissions, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
